---
# tasks file for maria_db

- name: Install 'mariadb-server'
  yum:
    name: mariadb-server
    update_cache: true
    state: present

- name: Install 'MySQL-python'
  yum:
    name: MySQL-python
    update_cache: true
    state: present

- name: Insert firewalld rule for {{ mysql_port }}/tcp port
  firewalld:
    port: "{{ mysql_port }}/tcp"
    permanent: true
    state: enabled
    immediate: true
  ignore_errors: true

- name: Ensure 'mariadb' service is started and enabled
  service:
    name: mariadb
    state: started
    enabled: true

- name: Create "{{ db_name }}" database
  mysql_db:
    name: "{{ db_name }}"
    state: present

- name: >
    Create database user "{{ db_user }}"
    with "{{ db_name }}.*:ALL" privileges
  mysql_user:
    name: "{{ db_user }}"
    password: "{{ db_password }}"
    priv: "{{ db_name }}.*:ALL"
    state: present
  no_log: true