---
- name: Configure web server with own-signed tls-cert
  hosts: nodes
  gather_facts: true
  become: false
  roles:
    - role: "webserver"
      tags: webserver

- name: Create a database with MariaDB
  hosts: nodes
  gather_facts: true
  become: true
  roles:
    - role: "maria_db"
      tags:
        - maria_db
    